project:
  name: quickstart-crest-infosolutions-cloudmeet
  owner: quickstart-eng@amazon.com
  package_lambda: false
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: 'quickstart-crest-infosolutions-cloudmeet/'
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  cloudmeet-us-east-1-3-AZ:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      CompanyName: 'taskcatq'
    regions:
      - us-east-1
    template: templates/cloudmeet-entrypoint-new-vpc.template.yaml
